### ISSUE TITLE
Show "One piece price" if more than 1 piece

### ISSUE THREAD

**Issue by raingart** [AndShy/Ali-Total-Price#1]

**Comment by AndShy** [comment]
doubtful decision, because that style dynamically changes page layout. 
better to use "visibility" style, but that also doubtful dicision, because that line also useful with fast comparison between 1 and 2 pcs/lot price. Quite often 1 pcs much cheaper than >1 pcs. 
simple example : ![img](https://i.imgur.com/pTnsWiF.jpg)

**Comment by raingart** [comment]
Yep, I did not think about.
You can add a comparison of prices before and after. And when it is different to display info. 
But this is an unjustified complication of the script logic.

But still, showing "One piece price" when buying 1 product is also strange.

>better to use "visibility" style

p.s. "visibility: hidden;" does not hide `margin/padding` indents. Leaves them unlike "display".
Definitely better to use `div.classList.toggle ("visible")`. But I was too lazy. The task was to demonstrate the "problem" to you.

**Comment by AndShy** [comment]
>"visibility: hidden;" does not hide margin/padding indents

That's the idea. Changing page/elements layout a lot worse for me than the just leave some blank space. 
>You can add a comparison of prices before and after. And when it is different to display info.

You can try it by yourself, but I'm see differences at each increment. In that case will be better to form table, but it also doubtful dicision. 

>The task was to demonstrate the "problem" to you.

I'm uderstand. Thanks for that.

**Comment by raingart** [comment]
I thought for a while and found a solution.
The problem is that "One piece price" and "Tital price" are equal, and duplicate each other.

This [fix](https://github.com/raingart/Ali-Total-Price/commit/846084631aab77062794fe4017730c619ca1bf84#diff-264763acc13e705dacd5ec9cbb20b63bR138) should fix the problem

**Comment by raingart** [comment]
off topic
I saw that you made a fork of Youtube plus (ParticleCore). While the author once again rewrites the extension. I made [my own](https://github.com/raingart/New-Horizons-for-YouTube-extension) based on plugins.
I'm interested in your opinion. It works slower than ParticleCore, but it seems to me it will be easier to figure it out for another person. Probably a plug-in system will avoid conflicts with other extensions.
I spoke with the author of ParticleCore, and as I understand it, he will make the new extension monolithic.

**Comment by AndShy** [comment]
>This fix should fix the problem

my solution : 
`pcs_container.style.visibility = quantInp.value > 1 ? 'visible' : 'hidden';`
no need to calculate `(tp/+quantInp.value) === tp`
but, as I say - I'm needing to fast compare  prices for 1pcs/lot. faster method - to compare on one line with increase/decrease quantity
>I'm interested in your opinion.

my opinion is to use old style youtube with adblock, with 1080p30fps, with "teatre mode". Old ParticleCore give me that after some code fixing.  I'm look at you solution when old style youtube will be no longer exist

**Comment by AndShy** [comment]
PS: also I need function wich stop videos loading, cuz I'm opening many tabs from subscription feed.

**Comment by raingart** [comment]
`(tp/+quantInp.value) === tp` agree stupid decision. I don’t know why I chose it.
I wanted to find the remainder of dividing the price for several products and compare it with the total cost. But there was no easy way how to implement this in your script. And the result was a piece of code.

**Comment by AndShy** [comment]
>I wanted to find the remainder of dividing the price for several products and compare it with the total cost

oooook ?... but total price = `(base price * quantity + shipping cost)` and price for 1 pcs/lot = `(base price * quantity + shipping cost)/quantity` . You can only compare total price and price for 1pcs if quantity=1 , otherwise it has no sense. 
And in that case `1pcs_price = total_price/1 = total_price`    :)

**Comment by AndShy** [comment]
I don't understand what you want to do. You only possible to add shipping cost divided by quantity, but I see no sense in that. All other datas are present. Another one option is to calculate difference between few 1pcs/lot price and form table depending on difference (maybe even plot).

**Comment by raingart** [comment]
I had a little shock from the information that you indicated. About a non-linear increase in the cost of goods when ordering 2 goods.

Initially, I was looking for an extension that simply added up supply and price. And I saw you have a price for 1 product. I thought that it was generally useless. And more is needed for wholesale buyers.

In the second message, you indicate that sometimes it’s more profitable to buy one product than a group. And I thought that it was necessary to deduce the cost of this product only when it is more expensive than several.The only solution that came up with is the remainder of the division. without using an array (anything like db)

**Comment by raingart** [comment]
Sorry if I confused you. Such a simple problem and so many messages. I don’t think the “problem” so significant was worth it

**Comment by AndShy** [comment]
the joke is that I do not see any problems :) I was need all that datas and I was implement it in script. 
Ok. I'm closing issue.
