### ISSUE TITLE
New Update?

### ISSUE THREAD

**Issue by gabxln** [AndShy/Ali-Total-Price#11]
Hi, 
I don't know if this is the place to write this.. 
I love this script, it just doesn't work anymore, please update? ✌

**Comment by dragoncity17** [comment]
Try : 
https://github.com/AndShy/Ali-Total-Price/blob/master/Ali_Total_Price.user_2.10_WIP.js

**Comment by gabxln** [comment]
> Try : https://github.com/AndShy/Ali-Total-Price/blob/master/Ali_Total_Price.user_2.10_WIP.js

thanks, now it's working lol

**Comment by AndShy** [comment]
new version released

**Comment by dragoncity17** [comment]
Hello @AndShy 
I tested your last release but doesn't work.

Only Ali_Total_Price.user_2.10_WIP.js work for me.

Maybe you can update with this version who work :)

thanks for all !

**Comment by AndShy** [comment]
Hi, @dragoncity17.
Can you take a screenshot of page and in development console with new version? 
I rewrote almost nothing since last 2.10 version, fixed few bugs with "new user promotion" and etc., and rewrote regular expression for extracting values. So new version should work fine

**Comment by dragoncity17** [comment]
as you can see the version "Only Ali_Total_Price.user_2.10_WIP." on top works while the last one does not.
![1](https://user-images.githubusercontent.com/19295070/180026269-28ab461e-d159-4d61-bc60-181575ac636d.png)
![2](https://user-images.githubusercontent.com/19295070/180026287-4659ba2b-f23b-436f-89bc-d88d6730a528.png)

**Comment by dragoncity17** [comment]
EDIT : I found the problem.

I want to test without disable previous version.

And need only 1 script at the same time.

Now work ! :)

Sorry ;)

So maybe next time update for include search page ?

**Comment by AndShy** [comment]
I was going to say same thing about 2 working scripts at the same time 😁
There's some problems with search pages. Main is the ali not always shows shipping cost.
