### ISSUE TITLE
Uses inflated price instead of actual price

### ISSUE THREAD

**Issue by Wlodarski** [AndShy/Ali-Total-Price#12]
Fetches the price from _product-price-original_ div instead of the _product-price-current_ div.
![Clipboard02](https://user-images.githubusercontent.com/28050769/232228073-7d573d3f-23ae-4f86-ada1-d8f1b2fb54f2.jpg)

**Comment by AndShy** [comment]
Should work now. Needs further testing

**Comment by AndShy** [comment]
there is another issue:
https://github.com/AndShy/Ali-Total-Price/issues/13#issue-1669485518

**Comment by Wlodarski** [comment]
At first glance, seems to me that line 114 should be ` var itemPriceEl = document.querySelector('div.product-price-current > div');`

**Comment by AndShy** [comment]
Still doesn't work?
For me working good "div.product-price-current > span" 
And as I say - atm AliExpress have too many site layouts

**Comment by Wlodarski** [comment]
First of all, in the current code, at line 114, you have `var itemPriceEl = document.querySelector('div.product-price-current > span.product-price-value');` not `var itemPriceEl = document.querySelector('div.product-price-current > span');`.

Just `> span` cannot work because the price is currently distributed by AliExpress in several spans :

```
<div class="product-price-current">
  <div class="_1Hlfk notranslate" style="font-size: 15px;">
     <span class="RqgnK" data-spm-anchor-id="a2g0o.detail.1000016.i3.7ab77796ctmjVZ">C$</span>
     <span class="_2e8No"></span>
     <span class="wJAFI">1</span>
     <span class="wJAFI">3</span>
     <span class="RqgnK">.</span>
     <span class="RqgnK" data-spm-anchor-id="a2g0o.detail.1000016.i4.7ab77796ctmjVZ">9</span>
     <span class="RqgnK">0</span>
   </div>
</div>
```

With `var itemPriceEl = document.querySelector('div.product-price-current > div');` for me everything works fine, as it used to.

**Comment by AndShy** [comment]
> First of all, in the current

Yeah, I know. Just wrote answer from phone. 

> Just > span cannot work because the price is currently distributed by AliExpress in several spans :

Are you sure? :smirk:
![2023-04-17 3](https://user-images.githubusercontent.com/15649615/232586316-392d94e9-c0d9-4b8f-98a0-cf25e775a3f0.png)

it's just Chinese technologies of future - from now on every user have it's own site version :pensive:

**Comment by Wlodarski** [comment]
![Clipboard01](https://user-images.githubusercontent.com/28050769/232588715-cbf751a9-8bdb-4bb8-bb7c-0f2f90d6dbdc.jpg)

**Comment by AndShy** [comment]
Ok. But I don't know how it's working and I haven't words to comment it.

**Comment by Wlodarski** [comment]
I think the script sees the content of the div, ignoring the span tags. So, it concatenates all the text into a meaningful string, `C$ 63.15`.

**Comment by AndShy** [comment]
I don't mean a script, but a site. I don't even know how to test script, if there is so many versions of same site o_0

**Comment by Wlodarski** [comment]
The solution is simple. You need to change to the selector on lines 44 and 67 to `currency = document.querySelector("#switcher-info > span.currency");` as it not anymore `a#switcher-info > span.currency`

**Comment by AndShy** [comment]
All of this is simple for me. But I don't see a reason to fix something, because AliExpress has too many versions of layout for same site. I would even say it has different version for each user

**Comment by Wlodarski** [comment]
> it has different version for each user

You exaggerate. From time to time, some element gets updated. That's all. The page structure is the same for all users. You just didn't bother to look what changed, hoping somebody else, like me, would update the script for you.

**Comment by AndShy** [comment]
I propose a bet: 
if I post 3 versions of the site design tomorrow, you will admit that you are a complete idiot. 
Deal?

**Comment by Wlodarski** [comment]
> I propose a bet:
> if I post 3 versions of the site design tomorrow, you will admit that you are a complete idiot.
> Deal?

I will refrain from competing with your lack of maturity and instead, I will discontinue extending my assistance. I will proceed with updating the script by myself for myself, just as I have been doing so far.  Until you learn to work collaboratively with others, you will be constantly frustrated and feel that even the simplest of scripts is an insurmountable task.

**Comment by gabxln** [comment]
Please stop fighting guys.
I love this script and i need you guys to update the script and other people too :(

**Comment by AndShy** [comment]
> I will refrain from competing with your lack of maturity 

it's easier to write some pseudo-intellectual garbage than to answer for your words. Just admit that you are a complete idiot
![2023-05-06 120511](https://user-images.githubusercontent.com/15649615/236626424-c46f81c8-0c88-48ec-a099-e9b0519a92ec.png)
![2023-05-06 120648](https://user-images.githubusercontent.com/15649615/236626432-c954b05f-b0c4-452f-be93-8fa72002358e.png)
![2023-05-06 120751](https://user-images.githubusercontent.com/15649615/236626442-0c5b76f9-502c-4568-93ba-a9b7ca5fa677.png)
![2023-05-06 120825](https://user-images.githubusercontent.com/15649615/236626450-baec5c8f-6b89-45a2-8690-06b20b7eade2.png)
![2023-05-06 122000](https://user-images.githubusercontent.com/15649615/236626459-0c507f2d-fd78-4622-91b4-4967ae9e1bc1.png)
![2023-05-06 122111](https://user-images.githubusercontent.com/15649615/236626468-a41440a7-330b-4a31-af0a-fb8ffdc6f2f2.png)
![2023-05-06 122219](https://user-images.githubusercontent.com/15649615/236626472-6f8fe972-c004-40a1-ad2f-1b66eb769509.png)
![2023-05-06 143728](https://user-images.githubusercontent.com/15649615/236626480-090a23c7-c408-493e-8332-6a1203537f1b.png)
![2023-05-06 143752](https://user-images.githubusercontent.com/15649615/236626486-b9af12dd-a939-4d84-a3db-a860da33ac00.png)
![2023-05-06 143849](https://user-images.githubusercontent.com/15649615/236626491-fd2d5dd9-c5d0-40df-b1e2-eb60f7c9351b.png)
![2023-05-06 143922](https://user-images.githubusercontent.com/15649615/236626498-5c8e8e10-d46d-4401-9300-eeea4b434fd5.png)
![2023-05-06 144226](https://user-images.githubusercontent.com/15649615/236626504-bc3faaa0-9c03-4da1-bf1a-aab1b30bea84.png)
![2023-05-06 144838](https://user-images.githubusercontent.com/15649615/236626509-c0ee4cef-36b1-4290-9855-b4cbccfc836d.png)

> I will discontinue extending my assistance

Your assistance? WHERE? :frowning:  1 opened issue? Oh nooooo, don't do that! Without you I'll don't know that aliexpress has over 9000 designs and script won't work for most peoples without rewriting for all of this designs 

![2023-05-06 151952](https://user-images.githubusercontent.com/15649615/236626888-e5c08940-e329-40a6-9fbb-65fd8071bde1.png)
![2023-05-06 152024](https://user-images.githubusercontent.com/15649615/236626897-bc795021-2210-4f9d-bb4d-86cd998ddd91.png)
![2023-05-06 152042](https://user-images.githubusercontent.com/15649615/236626900-13f0c5f7-0b30-46b9-8d1d-5d0f95c06ce9.png)

> I will proceed with updating the script by myself for myself, just as I have been doing so far.

Instead, you can fork the script and maintain it for everyone, not just yourself. Why don't you want to do it? All i hear is just blah blah blah

**Comment by Wlodarski** [comment]
> Just admit that you are a complete idiot
> Your assistance? WHERE?

After insulting me, you finally applied the [first](https://github.com/AndShy/Ali-Total-Price/issues/12#issuecomment-1510518033) and [second](https://github.com/AndShy/Ali-Total-Price/issues/12#issuecomment-1536839243) corrections I've submitted instead of acting like a child, and now the bug is gone. But not without [pretending you fixed it](https://github.com/AndShy/Ali-Total-Price/issues/14#issuecomment-1537431895).

**Comment by AndShy** [comment]
>Just admit that you are a complete idiot

and gfys
