### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by gabxln** [AndShy/Ali-Total-Price#14]
Stop Working again.

**Comment by AndShy** [comment]
https://github.com/AndShy/Ali-Total-Price/issues/13#issue-1669485518

**Comment by AndShy** [comment]
https://github.com/AndShy/Ali-Total-Price/issues/12#issuecomment-1511110772

**Comment by AndShy** [comment]
Ok. I can fix script for you, but firstly I need to see what your ali design is. So post a screenshot. Also tell what problem is. Just not working?

**Comment by gabxln** [comment]
Well, I don't know if the language makes a difference... 
and yes, it just doesn't work, nothing appears.

![Captura de tela 2023-05-06 184205](https://user-images.githubusercontent.com/107080676/236647908-e05dc38e-b919-43e3-9d1b-aec2f382fbd4.png)
![Captura de tela 2023-05-06 184246](https://user-images.githubusercontent.com/107080676/236647911-df0275e6-ae5e-4546-80e5-898f9795ea84.png)
![Captura de tela 2023-05-06 185325](https://user-images.githubusercontent.com/107080676/236648091-057094b5-15ab-4b1d-ba4c-1feb0420306a.png)

**Comment by AndShy** [comment]
should work now. 
as write [Wlodarski](https://github.com/Wlodarski) there is some changes in price style most likely for countries of america, and changes in country/language/currency block most likely for everyone. 
if not work - logout from ali, ctrl+shift+i or F12 >in "elements" select second line with "html ..." > right click > edit as html > copy all, save in txt and send me. 
[Ali_Total_Price_2.14_countries_of_america.user.js.zip](https://github.com/AndShy/Ali-Total-Price/files/11414903/Ali_Total_Price_2.14_countries_of_america.user.js.zip)

**Comment by dragoncity17** [comment]
Hello AndShy ! :)

I am from EU, and previous script doesn't work (nothing...), but for this script [Ali_Total_Price_2.14_countries_of_america.user.js.zip]" I have :

One piece/lot price:  ---
Total Price:  ---

>> **For price :**
# HTML
`<span class="product-price-value">€ 2,01</span> `
# SELECTOR
`#root > div > div.product-main > div > div.product-info > div.product-price > div.product-price-current > span `

>> **For shipping :**
# HTML
`<strong data-spm-anchor-id="a2g0o.detail.1000016.i5.676b414e0gmzAc">Livraison: € 2.27</strong>`
# SELECTOR
`#root > div > div.product-main > div > div.product-info > div.product-dynamic-shipping > div > div > div.dynamic-shipping-line.dynamic-shipping-titleLayout > span > span > strong`


I hope can help ! :)

**Comment by AndShy** [comment]
[dragoncity17](https://github.com/dragoncity17)
I have changed selector for currency and have 'fixed' bug with shipping cost in master branch script. try it. 
but script needs further rewriting due to some changes and many of item page designs, so script may be not always working correctly

**Comment by dragoncity17** [comment]
Great !!!! Work ! :)

Good job, I know it's Ali Express the problem ^^

**Comment by gabxln** [comment]
> should work now. as write [Wlodarski](https://github.com/Wlodarski) there is some changes in price style most likely for countries of america, and changes in country/language/currency block most likely for everyone. if not work - logout from ali, ctrl+shift+i or F12 >in "elements" select second line with "html ..." > right click > edit as html > copy all, save in txt and send me. [Ali_Total_Price_2.14_countries_of_america.user.js.zip](https://github.com/AndShy/Ali-Total-Price/files/11414903/Ali_Total_Price_2.14_countries_of_america.user.js.zip)

Works now friend 😀 Thank You
