### ISSUE TITLE
VAT

### ISSUE THREAD

**Issue by Springers** [AndShy/Ali-Total-Price#3]
Hi.
Would it be possible to add VAT to the total price?
After July 1, 2021 changes for EU citizens, I really would benefit from this, if it is in anyway possible :)

**Comment by AndShy** [comment]
As I can see that possible only through in script calculating, because I don't see any VAT information on items pages 
![image](https://user-images.githubusercontent.com/15649615/124640600-eba2c480-de8d-11eb-8110-45cebbd13c93.png)

**Comment by AndShy** [comment]
also I found this: 
![image](https://user-images.githubusercontent.com/15649615/124642400-18f07200-de90-11eb-924a-2c24421f7a55.png)
so, for precise calculation needs to implement manual input your country VAT value

**Comment by Springers** [comment]
Yeah, you are right, they calculate it at checkout.. and it changes per country.. thank you for looking into it. :)

**Comment by AndShy** [comment]
in few days I'll try to realize fork for EU users with manually set up VAT

**Comment by AndShy** [comment]
ok. here is beta version. needs testing : https://github.com/AndShy/Ali-Total-Price/raw/master/Ali_Total_Price_EU_VAT.user.js
![image](https://user-images.githubusercontent.com/15649615/125333355-7120eb80-e34a-11eb-9d7c-c117372c413c.png)

**Comment by Springers** [comment]
Looks to be working good so far.
I had to put treshold to 1 for it to work.

**Comment by AndShy** [comment]
~~threshold is minimum price + shipping value to apply VAT. in most EU countries it around 20-22 euro~~
my bad. I read the old information about VAT. correct rules is:  if price below 150 eur VAT must be paid on online trade platforms, otherwise VAT must be paid on custom. 
I'll rewrite script a little. atm you can simply put 0 into threshold.

**Comment by AndShy** [comment]
Udpated version uploaded.

**Comment by Springers** [comment]
Works fine here.
