### ISSUE TITLE
TOTAL doesn't work

### ISSUE THREAD

**Issue by dragoncity17** [AndShy/Ali-Total-Price#6]
Before work, and now doesn't work like you can see :
![téléchargement](https://user-images.githubusercontent.com/19295070/138054990-4754168f-64ca-4924-aa53-f62f66b9da00.png)

Thank you in advance for fix ! :)

Your script is very good ! :)

**Comment by AndShy** [comment]
idk what's wrong in your browser, but script still working for me. 
Vivaldi  4.3.2439.44 (Stable channel)
![image](https://user-images.githubusercontent.com/15649615/138086395-24322413-ee06-4a6d-874a-fd904727502c.png)
old opera 58.0.3135.127: 
![image](https://user-images.githubusercontent.com/15649615/138086942-ee3141bf-ff52-4162-9910-c595c97cbd0b.png)
same with EU VAT version of script

attach log file from dev console: F12 -> console tab -> RMB in console -> save as...

**Comment by AndShy** [comment]
also log out from aliexpress and attach file with DOM elements: F12 -> elements tab -> select <html .........> line -> RMB ->copy -> copy outerHTML -> save copied text in txt file

**Comment by dragoncity17** [comment]
I use chrome.

Strange because before work.. and now no... o_O

I went to console... maybe you will find the problem .

(I saw you are french like me ! :) )

![zzzzz](https://user-images.githubusercontent.com/19295070/138090185-8acfe06d-23c4-4bb8-a974-a1bd1cf9e71b.png)
:

**Comment by dragoncity17** [comment]
![azeazaza](https://user-images.githubusercontent.com/19295070/138090318-8c2b1bdd-8e77-4b83-8396-c3565684536b.png)

**Comment by AndShy** [comment]
>  (I saw you are french like me ! :) )

absolutely no :)

if you want to do it by yourself then check this elements on ali item page: 
```
        ('div.product-sku');
        ('span.next-input.next-medium.next-input-group-auto-width > input');
        ('div.product-shipping');
        ('a#switcher-info > span.currency')
        ('span.product-price-piece');
        ('div.product-shipping-price > span.bold');
        ('span.next-input.next-medium.next-input-group-auto-width > input');
        ('span.product-price-value');
```
ali regulary change class names and script stop working. but atm I can only knew a problem on russian page, but russian version almost independent version of aliexpress.

**Comment by AndShy** [comment]
important elements

![image](https://user-images.githubusercontent.com/15649615/138093245-088a8a52-5e53-4d0e-8119-5d659755d889.png)
![image](https://user-images.githubusercontent.com/15649615/138093585-182c67ce-b23b-4289-b652-9eca666858a5.png)
![image](https://user-images.githubusercontent.com/15649615/138093768-919a4c74-14c4-492e-8b78-3f78554cda40.png)
![image](https://user-images.githubusercontent.com/15649615/138093896-960f8f49-9341-4aeb-8db1-5f375803cec4.png)
![image](https://user-images.githubusercontent.com/15649615/138094402-8b2119b7-5704-45dc-93d4-72150b8fadce.png)

**Comment by dragoncity17** [comment]
Ok I found... because it worked with an chrome portable.

In fact it was "cookies" the problem, I delete ALL and now work.

Thank you for your help and your amazing script ! :)

**Comment by AndShy** [comment]
you're welcome. also you can try to enable extension in private mode (tampermonkey).

**Comment by dragoncity17** [comment]
For information need to block "cna" cookies with "EditThisCookies" extension.
If not every time doesn't work.

**Comment by AndShy** [comment]
Aliexpress randomly for some users changes style, so in your case (and now in mine too. only in one browser) "ali total price" won't work. 
![image](https://user-images.githubusercontent.com/15649615/139091205-8c04d656-2193-499a-ba5d-ad26f4d76dea.png)
Ali changed only shipping cost block, so I fixed script. Atm script in WIP stage until aliexpress permanently change style. 
[Ali_Total_Price.user_2.10_WIP.js](https://github.com/AndShy/Ali-Total-Price/blob/master/Ali_Total_Price.user_2.10_WIP.js)
copy code and replace it in tampermonkey manually.

**Comment by AndShy** [comment]
another small fix for 
`var quantInpEl = document.querySelector('span.next-input.next-medium.product-price-value > input');`
in to 
`var quantInpEl = document.querySelector('span.next-input.next-medium.next-input-group-auto-width > input');`
_(quantity observer)_
same link.

**Comment by AndShy** [comment]
another fixes for fixes :smile: 
hope final one
same link

**Comment by dimmuboy** [comment]
Works for me

**Comment by Oskimark** [comment]
can someone  helpme modify the script to make it work now?  
seems like ali changed the code again

**Comment by AndShy** [comment]
WIP version with fixes released to master branch
