### ISSUE TITLE
Tampermonkey compatibility

### ISSUE THREAD

**Issue by Korb** [AndShy/Ali-Total-Price#9]
When opening [the script code](https://raw.githubusercontent.com/AndShy/Ali-Total-Price/master/Ali_Total_Price.user_2.10_WIP.js) in Mozilla Firefox 96.0b3 (64-bit), the installed Tampermonkey 4.13.6136 does not offer to install it.

**Comment by AndShy** [comment]
It's because script should ends with ".user.js"
